os: linux
dist: trusty
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y ack-grep cpanminus libperl-dev make perl python-glade2 python-gnome2 python-gnome2-dev python-gtk2 python-setuptools python-tk python3 python3-pip python3-setuptools python3-tk
    - sudo dpkg-divert --local --divert /usr/bin/ack --rename --add /usr/bin/ack-grep
install:
    - sudo cpanm Perl::Tidy Test::Code::TidyAll Test::Differences Test::TrailingSpace
    - "`which python3` -m pip install --upgrade --user flake8 pycotap random2 six"
    - "sudo /usr/bin/python3 -m pip install --upgrade pycotap random2 six"
    - "`which python` -m pip install --upgrade --user pycotap random2 six"
    - which python
script: "sh -x scripts/travis-ci-build"
